services:
  printproxy.hub:
    build:
      context: .
      dockerfile: PrintProxy.Hub/Dockerfile
    ports:
      - '8181:8080'
    depends_on:
      - db
    environment:
      - PRINTER_CONFIG=/PrinterConfig/PrinterConfig.json
      - GCODE_FILE_DIR=/GcodeFiles
    volumes:
      - PrinterConfig:/PrinterConfig
      - GcodeFiles:/GcodeFiles:rw
    healthcheck:
      test: ["CMD","curl","--silent","--fail","http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
   image: postgres
   restart: always
   volumes:
    -  PostgressData:/var/lib/postgresql
   environment:
     POSTGRES_PASSWORD: postgress
   healthcheck:
    test: ["CMD", "pg_isready", "-U", "postgres"]
volumes:
  PostgressData:
  PrinterConfig:
  GcodeFiles: