services:
  printproxy.hub:
    image: ${DOCKER_REGISTRY-}printproxyhub
    build:
      context: .
      dockerfile: PrintProxy.Hub/Dockerfile
    depends_on:
      - db
    environment:
      - PRINTER_CONFIG=/PrinterConfig/PrinterConfig.json
    volumes:
      - PrinterConfig:/PrinterConfig
  db:
   image: postgres
   restart: always
   volumes:
    -  PostgressData:/var/lib/postgresql 
   environment:
     POSTGRES_PASSWORD: postgress

volumes:
  PostgressData:
  PrinterConfig: