services:
  printproxy.hub:
    build:
      context: .
      dockerfile: PrintProxy.Hub/Dockerfile
    ports:
      - '8181:8080'
    depends_on:
      - db
    environment:
      - PRINTER_CONFIG=/PrinterConfig/PrinterConfig.json
      - GCODE_FILE_DIR=/GcodeFiles
    volumes:
      - PrinterConfig:/PrinterConfig
      - GcodeFiles:/GcodeFiles 
  db:
   image: postgres
   restart: always
   volumes:
    -  PostgressData:/var/lib/postgresql 
   environment:
     POSTGRES_PASSWORD: postgress

volumes:
  PostgressData:
  PrinterConfig:
  GcodeFiles: