services:
  printproxy.hub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - TZ=Europe/Copenhagen
    ports:
      - "8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./PrintProxy.Hub/PrinterConfig.json:/PrinterConfig/PrinterConfig.json
  db:
    ports:
      - 5433:5432
    environment:
      - TZ=Europe/Copenhagen
  valkey:
    ports:
      - 6380:6379
    environment:
      - TZ=Europe/Copenhagen